"""added status column for simulations

Revision ID: 162682acb8bc
Revises: eb33ae907f41
Create Date: 2026-03-26 10:36:42.339905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162682acb8bc'
down_revision = 'eb33ae907f41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_models', sa.Column('status', sa.String(), server_default='uploaded', nullable=False))
    op.create_index(op.f('ix_simulation_models_status'), 'simulation_models', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_models_status'), table_name='simulation_models')
    op.drop_column('simulation_models', 'status')
    # ### end Alembic commands ###
