"""make sensor external id unique per family

Revision ID: 17bbf914f49d
Revises: a1421aecca45
Create Date: 2026-08-27 11:22:10.328381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bbf914f49d'
down_revision = 'a1421aecca45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensors_external_id_key', 'sensors', type_='unique')
    op.create_unique_constraint('uq_sensors_sensor_family_external_id', 'sensors', ['sensor_family', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sensors_sensor_family_external_id', 'sensors', type_='unique')
    op.create_unique_constraint('sensors_external_id_key', 'sensors', ['external_id'])
    # ### end Alembic commands ###
