"""Add Sensors & Observation Types/Values

Revision ID: 329c9fc29af3
Revises: d6e7f8a9b0c1
Create Date: 2026-08-25 08:28:16.929155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '329c9fc29af3'
down_revision = 'd6e7f8a9b0c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False, comment='Describes the content of the value (e.g. Power, Voltage, Luminosity).'),
    sa.Column('unit', sa.String(), nullable=False, comment='Describes the unit of the value (e.g. kWh, V, mA).'),
    sa.Column('key', sa.String(), nullable=False, comment='Identifier used to extract the value from an observation record. Could be a JSON dict key or a column name.'),
    sa.Column('sensor_family', sa.Text(), nullable=True, comment='Contains the brand/model family of the sensor observations of this type are extracted from, if applicable.'),
    sa.Column('type_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("sensor_family", "key", name="uq_observation_types_sensor_family_key",)
    )
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('sensor_family', sa.Text(), nullable=True, comment='Contains the brand/model family of the sensor, if applicable.'),
    sa.Column('sensor_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('space', sa.Text(), nullable=True),
    sa.Column('starting_date', sa.DateTime(timezone=True), server_default=sa.text("TIMESTAMPTZ '2026-01-01 00:00:00 UTC'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('observation_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('observation_type_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_type_id'], ['observation_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'observation_type_id', 'timestamp', name='uq_observation_values_sensor_type_timestamp')
    )
    op.create_index('ix_observation_values_sensor_timestamp', 'observation_values', ['sensor_id', 'timestamp'], unique=False)
    op.create_index('ix_observation_values_sensor_type_timestamp', 'observation_values', ['sensor_id', 'observation_type_id', 'timestamp'], unique=False)
    op.create_index('ix_observation_values_type_timestamp', 'observation_values', ['observation_type_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observation_values_type_timestamp', table_name='observation_values')
    op.drop_index('ix_observation_values_sensor_type_timestamp', table_name='observation_values')
    op.drop_index('ix_observation_values_sensor_timestamp', table_name='observation_values')
    op.drop_table('observation_values')
    op.drop_table('sensors')
    op.drop_table('observation_types')
    # ### end Alembic commands ###
