"""added filename in BIM model

Revision ID: 5c2d18ef0061
Revises: 8dfd421f6b1f
Create Date: 2026-02-19 11:13:38.423314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2d18ef0061'
down_revision = '8dfd421f6b1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bim_models', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bim_models', 'filename')
    # ### end Alembic commands ###
