"""add bim_models

Revision ID: 8dfd421f6b1f
Revises: e2f75e3cf348
Create Date: 2026-02-10 16:08:12.906444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dfd421f6b1f'
down_revision = 'e2f75e3cf348'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bim_models_created_at'), 'bim_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_bim_models_file_id'), 'bim_models', ['file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bim_models_file_id'), table_name='bim_models')
    op.drop_index(op.f('ix_bim_models_created_at'), table_name='bim_models')
    op.drop_table('bim_models')
    # ### end Alembic commands ###
