"""added simulation metada table

Revision ID: eb33ae907f41
Revises: 5c2d18ef0061
Create Date: 2026-03-26 10:19:10.876658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb33ae907f41'
down_revision = '5c2d18ef0061'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_models_created_at'), 'simulation_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulation_models_file_id'), 'simulation_models', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_models_file_id'), table_name='simulation_models')
    op.drop_index(op.f('ix_simulation_models_created_at'), table_name='simulation_models')
    op.drop_table('simulation_models')
    # ### end Alembic commands ###
